### ISSUE TITLE
Ordnerauswahl

### ISSUE THREAD

**Issue by zonky2** [BugBuster1701/integrity_check#56]
Hallo BB,

aus aktuellem Anlass 

https://community.contao.org/de/showthread.php?50372-Dateiver%E4nderung-nach-FTP-Hack

habe ich mir die Erweiterung angesehen - wäre auch eine Auswahl eines Ordners möglich...??

Ich klick mir ja sonst die Finger wund, um alle Dateien einzubinden.

Gruss zonky

**Comment by BugBuster1701** [comment]
Hinweis: filetree und eval->path für Individuelles Wurzelverzeichnis für Dateibäume.

**Comment by BugBuster1701** [comment]
keine Features mehr für Contao 3 Erweiterungen
