### ISSUE TITLE
MD5 Checksummen für 3.2.21

### ISSUE THREAD

**Issue by jammon88** [BugBuster1701/integrity_check#77]
Hi

Can you please add the checksum for Contao 3.2.21?

Or how can I generate the checksum by myself?

Regards Jammon

**Comment by BugBuster1701** [comment]
Oh Thanks, I forgot that. Now in Integrity Check version 3.5.3

**Comment by jammon88** [comment]
Thanks for your very fast fix! That works perfect for me.
